flowchart LR

    A[Collect & Prepare Data]
    --> B[Train Model]
    --> C[Evaluate Model]
    --> D[Deploy Model]
    --> E[Receive New Data]
    --> F[Generate Predictions]
    --> G[Business Action]

    G -. Feedback .-> A