flowchart LR

    A[Raw Data]
    --> B[Processing<br/>Prepare]
    --> C[Ground Truth<br/>Label]
    --> D[Algorithms<br/>Train]
    --> E[Autopilot<br/>Auto Train & Tune]
    --> F[Model Registry<br/>Version & Store]
    --> G[Endpoints<br/>Deploy & Inference]